import * as React from 'react';
import Accordion from '@mui/material/Accordion';
import AccordionDetails from '@mui/material/AccordionDetails';
import AccordionSummary from '@mui/material/AccordionSummary';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Link from '@mui/material/Link';
import Typography from '@mui/material/Typography';

import ExpandMoreIcon from '@mui/icons-material/ExpandMore';

const FAQs = [
  {
    question: 'How does the AI identify skin diseases?',
    answer:
      'Our AI uses advanced image recognition and machine learning algorithms trained on a vast dataset of dermatological conditions to accurately identify skin diseases.',
  },
  {
    question: 'Can I communicate with my patients through the platform?',
    answer:
      'Yes, our platform offers a secure chat and video call feature that allows you to communicate directly with your patients, providing real-time consultations and follow-ups.',
  },
  {
    question: 'How can I track UV index levels for my patients?',
    answer:
      'Our UV Index Tracking feature provides real-time data on UV radiation levels, helping you offer personalized advice to your patients on skin protection and outdoor safety.',
  },
  {
    question: 'What kind of reports can be generated by the system?',
    answer:
      'The system can generate comprehensive patient reports that include diagnosis details, treatment plans, and recommendations. These reports can be easily shared with patients and other healthcare providers in PDF',
  },
];

function FAQSection() {
  const [expanded, setExpanded] = React.useState(false);

  const handleChange = (panel) => (event, isExpanded) => {
    setExpanded(isExpanded ? panel : false);
  };

  return (
    <Container
      id="faq"
      sx={{
        pt: { xs: 4, sm: 12 },
        pb: { xs: 8, sm: 16 },
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: { xs: 3, sm: 6 },
      }}
    >
      <Typography
        component="h2"
        variant="h4"
        color="text.primary"
        sx={{
          width: { sm: '100%', md: '60%' },
          textAlign: { sm: 'left', md: 'center' },
        }}
      >
        Frequently asked questions
      </Typography>
      <Box sx={{ width: '100%' }}>
        {FAQs.map((faq, index) => (
          <Accordion
            key={index}
            expanded={expanded === `panel${index + 1}`}
            onChange={handleChange(`panel${index + 1}`)}
          >
            <AccordionSummary
              expandIcon={<ExpandMoreIcon />}
              aria-controls={`panel${index + 1}d-content`}
              id={`panel${index + 1}d-header`}
            >
              <Typography component="h3" variant="subtitle2">
                {faq.question}
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography
                variant="body2"
                gutterBottom
                sx={{ maxWidth: { sm: '100%', md: '70%' } }}
              >
                {faq.answer}
              </Typography>
            </AccordionDetails>
          </Accordion>
        ))}
      </Box>
    </Container>
  );
}

export default FAQSection;